post http://localhost:3000/api/authorize
Content-Type: application/json

{
    "id": "NS6FYmAUBGXUJrVnXCEB"
}

###

post http://localhost:3000/api/suggest-game
Content-Type: application/json

{
    "name": "Juego",
    "description": "sdfsddsfds",
    "urlPhoto":"https://storage.googleapis.com/web-prof.appspot.com/58033010_2050165915283594_6782158053677465600_n.jpg?GoogleAccessId=firebase-adminsdk-wysah%40web-prof.iam.gserviceaccount.com&Expires=4133829600&Signature=BfTz7NviGQGtWkhXSKzRccNjjD1rVnZaHiAeTZiG5SGkDG6rJApy%2FBlMhR6c%2BRjiLnWdxzMPvKt%2FJQY1%2F3RqxHCty07ha1ErNX0L8CXvu%2FSE%2BoNiLAIwpImudTOoWCRAdQ3GveLROFI2NpIXlLCyKcK7vxG%2BIvprzPdBOvp4V8cZsddeGG327RedrTVQ4X4JxSBcqEa%2BP2XN3P7SUCUmbyOvRgxqswWhmBlJP08%2F6YGCvANcLK2fvFsAN04Ry9iLBArJxIkOQxUX%2F%2FsUckQn1o1HIqui9Tg6ChkoYCkiO0bIGHOsvLH0UvaljDHrPjkDxFL35Y1iJFlpOoiEZOkG6A%3D%3D"

}

###
post http://localhost:3000/api/search
Content-Type: application/json

{
    "name": "gensh"
}
